//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryBD3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Library3Entities : DbContext
    {
        public Library3Entities()
            : base("name=Library3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditLibrary> AuditLibrary { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Publisher> Publisher { get; set; }
        public virtual DbSet<RelationAuthorBook> RelationAuthorBook { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
